//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class alert_message
    {
        public int id { get; set; }
        public string subject { get; set; }
        public string receipient { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> date_sent { get; set; }
        public string sender { get; set; }
    }
}
