//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class approval
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> approval_datetime { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> code { get; set; }
        public string @event { get; set; }
        public Nullable<bool> utilized { get; set; }
        public Nullable<bool> expired { get; set; }
    }
}
