//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class atc_card
    {
        public int id { get; set; }
        public Nullable<int> atc_id { get; set; }
        public Nullable<int> card_id { get; set; }
        public Nullable<bool> data_or_trade { get; set; }
        public string driver { get; set; }
        public string truck_no { get; set; }
        public string status { get; set; }
        public string atc_no { get; set; }
    }
}
