//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class atc_transactions
    {
        public int id { get; set; }
        public Nullable<int> atc_id { get; set; }
        public Nullable<System.DateTime> trx_datetime { get; set; }
        public Nullable<bool> sap_online { get; set; }
        public string doc_type { get; set; }
        public string doc_number { get; set; }
        public string username { get; set; }
    
        public virtual atc atc { get; set; }
    }
}
