//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class atc_audit
    {
        public int Id { get; set; }
        public Nullable<int> atc_id { get; set; }
        public string activity { get; set; }
        public string DoneBy { get; set; }
        public System.DateTime Date_Time { get; set; }
    }
}
