//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class atc_correction
    {
        public int id { get; set; }
        public string atc_no { get; set; }
        public string truck_no { get; set; }
        public string delivery_no { get; set; }
        public string trip_id { get; set; }
        public string new_trip_id { get; set; }
        public string loc { get; set; }
        public string new_loc { get; set; }
        public string shp_point { get; set; }
        public string new_shp_point { get; set; }
        public string serial_no { get; set; }
        public string new_serial_no { get; set; }
        public string reason { get; set; }
        public string approved_by { get; set; }
        public string operated_by { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string prev_picked_qty { get; set; }
        public string plant_code { get; set; }
        public string new_plant_code { get; set; }
    }
}
