//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class atc_session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public atc_session()
        {
            this.transaction_log = new HashSet<transaction_log>();
        }
    
        public int Id { get; set; }
        public string session_id { get; set; }
        public Nullable<System.DateTime> session_start { get; set; }
        public Nullable<int> start_approved_by { get; set; }
        public Nullable<System.DateTime> session_end { get; set; }
        public Nullable<int> end_approved_by { get; set; }
        public string status { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction_log> transaction_log { get; set; }
    }
}
