//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATCDriverRemark
    {
        public int id { get; set; }
        public Nullable<int> atc_driver_id { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
