//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class bin
    {
        public int id { get; set; }
        public string bin_code { get; set; }
        public string description { get; set; }
        public string type { get; set; }
        public Nullable<decimal> tare_weight { get; set; }
    }
}
