//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class block_reason
    {
        public int id { get; set; }
        public string block_code { get; set; }
        public string reason { get; set; }
        public Nullable<bool> delivery_block { get; set; }
    }
}
