//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class card_history
    {
        public int id { get; set; }
        public Nullable<int> atc_card_id { get; set; }
        public string status_event { get; set; }
        public Nullable<System.DateTime> date_executed { get; set; }
        public Nullable<int> user_id { get; set; }
        public string notes { get; set; }
        public string card_no { get; set; }
    }
}
