//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class change_request
    {
        public int id { get; set; }
        public string request_type { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> date_of_request { get; set; }
        public Nullable<System.DateTime> date_of_approval { get; set; }
        public Nullable<bool> approved { get; set; }
        public string notes { get; set; }
        public Nullable<int> user_id { get; set; }
        public string requested_by { get; set; }
        public Nullable<bool> rejected { get; set; }
    }
}
