//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class cng_master
    {
        public int id { get; set; }
        public string plant { get; set; }
        public Nullable<decimal> conv_f { get; set; }
        public Nullable<decimal> blend_r { get; set; }
        public Nullable<int> dsl_cap { get; set; }
        public Nullable<int> cng_cap { get; set; }
    }
}
