//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_back_up_07102021
    {
        public int Id { get; set; }
        public string customer_no { get; set; }
        public string customer_name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<bool> sms_enabled { get; set; }
        public Nullable<bool> whatsapp_enabled { get; set; }
    }
}
