//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        public int id { get; set; }
        public Nullable<int> weighbridge_id { get; set; }
        public string device_type { get; set; }
        public string ip_address { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string channel { get; set; }
        public string port { get; set; }
        public string baud { get; set; }
        public string parity { get; set; }
        public string data_bits { get; set; }
        public string sensor_index { get; set; }
        public string sensor_green { get; set; }
        public string traffic_index { get; set; }
        public string traffic_green { get; set; }
        public string status { get; set; }
    
        public virtual weighbridge weighbridge { get; set; }
    }
}
