//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocType
    {
        public int Id { get; set; }
        public string doc_type { get; set; }
        public string description { get; set; }
        public Nullable<int> number_prefix { get; set; }
        public Nullable<int> number_length { get; set; }
    }
}
