//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class eATC
    {
        public int id { get; set; }
        public string atc_no { get; set; }
        public string atc_type { get; set; }
        public string plant { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string from_city { get; set; }
        public string to_city { get; set; }
        public string to_city_actual { get; set; }
        public string contact_person { get; set; }
        public string delivery_address { get; set; }
        public string ack_flag { get; set; }
        public string contact_no { get; set; }
        public string doc_no { get; set; }
        public string dds_ack_flag { get; set; }
        public string state { get; set; }
        public string email_id { get; set; }
    }
}
