//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment_master
    {
        public int id { get; set; }
        public string equipment { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string fleet_section { get; set; }
        public string object_type { get; set; }
        public string object_number { get; set; }
    }
}
