//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment_detail_bkup_04062022
    {
        public int id { get; set; }
        public string object_number { get; set; }
        public string status { get; set; }
        public string status_inactive { get; set; }
    }
}
