//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class excel_batch
    {
        public int id { get; set; }
        public string filename { get; set; }
        public string username { get; set; }
        public string guid { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<int> count_in_excel { get; set; }
        public Nullable<int> count_uploaded { get; set; }
    }
}
