//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class excel_upload
    {
        public int id { get; set; }
        public string atc_no { get; set; }
        public string validation { get; set; }
        public string atc_type { get; set; }
        public Nullable<System.DateTime> date_uploaded { get; set; }
        public string uploaded_by { get; set; }
        public string status { get; set; }
        public Nullable<int> batch_id { get; set; }
    }
}
