//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class fuel_master
    {
        public int id { get; set; }
        public string source { get; set; }
        public string destination { get; set; }
        public Nullable<double> initial_km { get; set; }
        public Nullable<double> fuel_allowed { get; set; }
        public Nullable<double> fuel_allowance1 { get; set; }
        public Nullable<double> fuel_allowance2 { get; set; }
        public Nullable<double> fuel_allowance3 { get; set; }
        public Nullable<double> fuel_allowance4 { get; set; }
        public string city { get; set; }
        public Nullable<int> trip_days { get; set; }
    }
}
