//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class fuel_posting
    {
        public int id { get; set; }
        public string f_level { get; set; }
        public string station_code { get; set; }
        public string transporter { get; set; }
        public Nullable<int> trip { get; set; }
        public string tms_status { get; set; }
        public Nullable<bool> posted_to_sap { get; set; }
        public Nullable<System.DateTime> sap_time { get; set; }
    }
}
