//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class gate_access_log
    {
        public int id { get; set; }
        public string sales_doc_number { get; set; }
        public string truck_no { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> entry_datetime { get; set; }
        public Nullable<System.DateTime> exit_datetime { get; set; }
    }
}
