//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class gateaccess_info
    {
        public int id { get; set; }
        public string atc_no { get; set; }
        public string customer { get; set; }
        public string truck_no { get; set; }
        public string parent_so { get; set; }
        public string quantity { get; set; }
        public string driver { get; set; }
        public string license { get; set; }
        public Nullable<System.DateTime> entry_datetime { get; set; }
        public string username { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> exit_datetime { get; set; }
        public string transaction_type { get; set; }
        public string fleet_no { get; set; }
        public string shipping_point { get; set; }
        public string storage_location { get; set; }
    }
}
