//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class harvest
    {
        public int id { get; set; }
        public Nullable<int> estate_field_id { get; set; }
        public Nullable<System.DateTime> date_of_plant { get; set; }
        public Nullable<System.DateTime> dry_off_date { get; set; }
        public Nullable<System.DateTime> date_of_burning { get; set; }
        public Nullable<System.DateTime> date_of_harvest { get; set; }
        public Nullable<int> no_of_dry_offs { get; set; }
        public Nullable<System.DateTime> date_of_scrambled_cane { get; set; }
        public Nullable<decimal> estimated_yield { get; set; }
    }
}
