//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kna1
    {
        public int Id { get; set; }
        public string customer_code { get; set; }
        public string country { get; set; }
        public string name_1 { get; set; }
        public string name_2 { get; set; }
        public string city { get; set; }
        public string postal_code { get; set; }
        public string region { get; set; }
        public string search_term { get; set; }
        public string street { get; set; }
        public string telephone_1 { get; set; }
        public string fax_number { get; set; }
        public string one_time_account { get; set; }
        public string address { get; set; }
        public string address_name_1 { get; set; }
        public string address_name_2 { get; set; }
        public string address_city { get; set; }
        public string title { get; set; }
    }
}
