//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class loading_bay
    {
        public int id { get; set; }
        public string loadingbay_code { get; set; }
        public string loadingbay_name { get; set; }
        public string materials { get; set; }
        public Nullable<double> ave_processing_time { get; set; }
    }
}
