//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class loadingbay_queue
    {
        public int id { get; set; }
        public Nullable<int> bay_id { get; set; }
        public Nullable<int> trx_data_id { get; set; }
        public Nullable<System.DateTime> time_in { get; set; }
        public Nullable<System.DateTime> time_out { get; set; }
        public string status { get; set; }
        public Nullable<int> postion { get; set; }
        public Nullable<System.DateTime> processing_time { get; set; }
    }
}
