//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_file
    {
        public int id { get; set; }
        public string driver_id { get; set; }
        public string plant_code { get; set; }
        public string driver_fname { get; set; }
        public string driver_lname { get; set; }
        public string fleet { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> change_date { get; set; }
        public string license_num { get; set; }
        public string fleet_num { get; set; }
        public string identity_num { get; set; }
        public string issuing_authority { get; set; }
        public Nullable<System.DateTime> fp_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string issue_place { get; set; }
        public string issue_country { get; set; }
        public string phone { get; set; }
    }
}
