//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class module_access
    {
        public int Id { get; set; }
        public Nullable<int> role_id { get; set; }
        public string module { get; set; }
        public Nullable<bool> enable { get; set; }
    }
}
