//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class monthly_target
    {
        public int id { get; set; }
        public Nullable<int> target_year { get; set; }
        public Nullable<int> target_month { get; set; }
        public Nullable<decimal> target { get; set; }
    }
}
