//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class page_view
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_visited { get; set; }
        public Nullable<int> user_id { get; set; }
        public string username { get; set; }
        public string pageUrl { get; set; }
        public string ip_address { get; set; }
    }
}
