//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class plant
    {
        public int id { get; set; }
        public string plant_code { get; set; }
        public string city { get; set; }
        public string purchase_org { get; set; }
        public string sales_org { get; set; }
        public string plant_name { get; set; }
    }
}
