//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class raw_weigher_trx
    {
        public int id { get; set; }
        public Nullable<int> raw_weigher_id { get; set; }
        public string detail_type { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string time { get; set; }
        public Nullable<int> qty_int { get; set; }
        public Nullable<decimal> tonnage { get; set; }
        public Nullable<int> sugar_trx_id { get; set; }
    }
}
