//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class raw_weigher
    {
        public int id { get; set; }
        public string name { get; set; }
        public string serial_no { get; set; }
        public string ip_address { get; set; }
        public string port { get; set; }
        public string other { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}
