//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class region_data_bkup_06052023
    {
        public int Id { get; set; }
        public string area_sal_mgr { get; set; }
        public string location { get; set; }
        public string mandt { get; set; }
        public string reg_dir { get; set; }
        public string region { get; set; }
        public string sales_ref_ofcr { get; set; }
        public string sap_coding { get; set; }
        public string serial_no { get; set; }
        public string state { get; set; }
    }
}
