//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string mat_num { get; set; }
        public string goods_receipt { get; set; }
        public string plant { get; set; }
        public string storage_location { get; set; }
        public string description { get; set; }
        public string reservation_number { get; set; }
        public string material_doc_number { get; set; }
        public string created_by { get; set; }
        public string doc_no { get; set; }
        public string status { get; set; }
        public string type { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string UOM { get; set; }
        public Nullable<int> multiplier { get; set; }
    }
}
