//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class shift
    {
        public int id { get; set; }
        public string shift_name { get; set; }
        public Nullable<System.TimeSpan> time_start { get; set; }
        public Nullable<System.TimeSpan> time_end { get; set; }
        public Nullable<int> hours { get; set; }
    }
}
