//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class sto_data
    {
        public int Id { get; set; }
        public string po_doc_number { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> item_number { get; set; }
        public string material { get; set; }
        public string sales_order_item { get; set; }
        public Nullable<decimal> cumm_order_qty { get; set; }
        public string sales_unit { get; set; }
        public string customer_number { get; set; }
        public string customer_name { get; set; }
        public Nullable<decimal> del_qty { get; set; }
        public string sales_type { get; set; }
        public string plant_code { get; set; }
        public Nullable<bool> used { get; set; }
        public string sales_doc_type { get; set; }
        public string hash_sap { get; set; }
        public string delivery_block { get; set; }
        public string billing_block { get; set; }
        public string customer_block { get; set; }
        public string delivery_number { get; set; }
        public string trx_type { get; set; }
        public string delivery_number_out { get; set; }
        public string supplying_plant { get; set; }
        public string receiving_plant { get; set; }
    }
}
