//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_setting
    {
        public int Id { get; set; }
        public string system_state { get; set; }
        public string company_name { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public string sap_ip_address { get; set; }
        public string plant_code { get; set; }
        public string switch_over { get; set; }
        public Nullable<int> auto_threshold { get; set; }
        public Nullable<bool> demo_weigh_mode { get; set; }
        public Nullable<bool> use_transport { get; set; }
        public string bulk_procedure { get; set; }
        public Nullable<int> bulk_tolerance { get; set; }
        public string dispatch_tracker { get; set; }
        public string dispatch_tracker_exe { get; set; }
        public string locations { get; set; }
        public string shp_points { get; set; }
        public string sales_org { get; set; }
        public string materials { get; set; }
        public string country_code { get; set; }
        public Nullable<bool> use_gate_access { get; set; }
        public Nullable<bool> use_biometrics { get; set; }
        public Nullable<bool> use_wb_for_change { get; set; }
        public Nullable<bool> use_picking_for_change { get; set; }
        public string supplying_plant { get; set; }
    }
}
