//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracker
    {
        public int id { get; set; }
        public string activity { get; set; }
        public string ident { get; set; }
        public Nullable<System.DateTime> recorded_time { get; set; }
        public Nullable<int> status { get; set; }
    }
}
