//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_log
    {
        public int Id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> trx_date { get; set; }
        public string activity { get; set; }
        public string field_value { get; set; }
        public string atc { get; set; }
        public string field_name { get; set; }
        public Nullable<int> session_id { get; set; }
    
        public virtual atc_session atc_session { get; set; }
    }
}
