//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_data_back_up_14042022
    {
        public int id { get; set; }
        public string serial_no { get; set; }
        public string loc { get; set; }
        public string sales_doc_number { get; set; }
        public string shp_point { get; set; }
        public string trip_id { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string vehicle { get; set; }
        public string driver { get; set; }
        public string transporter { get; set; }
        public Nullable<decimal> gross { get; set; }
        public Nullable<decimal> tare { get; set; }
        public Nullable<decimal> nett { get; set; }
        public Nullable<System.DateTime> gross_time { get; set; }
        public Nullable<System.DateTime> tare_time { get; set; }
        public Nullable<bool> sync_status { get; set; }
        public string delivery_no { get; set; }
        public string error_field { get; set; }
        public string pgi_no { get; set; }
        public string waybill_no { get; set; }
        public string message_field { get; set; }
        public string tmp_delivery_no { get; set; }
        public string tmp_waybill_no { get; set; }
        public string sales_type { get; set; }
        public string transporter_name { get; set; }
        public Nullable<System.DateTime> picking_time { get; set; }
        public string parent_sales_order { get; set; }
        public string sender { get; set; }
        public string destination { get; set; }
        public string sales_doc_type { get; set; }
        public string operator_weighin { get; set; }
        public string operator_picking { get; set; }
        public string operator_weighout { get; set; }
        public string seal { get; set; }
        public string wb_in { get; set; }
        public string wb_out { get; set; }
        public Nullable<System.DateTime> sap_post_time { get; set; }
        public Nullable<System.DateTime> sap_response_time { get; set; }
        public Nullable<bool> sms_status { get; set; }
        public string code_a { get; set; }
        public string code_b { get; set; }
        public Nullable<int> item_number { get; set; }
        public string sales_order_item { get; set; }
        public string bin_1 { get; set; }
        public string bin_2 { get; set; }
        public Nullable<decimal> bin_1_tare { get; set; }
        public Nullable<decimal> bin_2_tare { get; set; }
        public Nullable<int> harvest_id { get; set; }
        public Nullable<int> plot_id { get; set; }
    }
}
