//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class transport_clearance
    {
        public int Id { get; set; }
        public Nullable<int> serial_no { get; set; }
        public System.DateTime doc_date { get; set; }
        public string waybill_no { get; set; }
        public Nullable<System.DateTime> waybill_date { get; set; }
        public Nullable<int> damage { get; set; }
        public Nullable<int> cake { get; set; }
        public Nullable<int> missing { get; set; }
        public Nullable<bool> cleared { get; set; }
        public Nullable<int> atc_id { get; set; }
        public string flag { get; set; }
    
        public virtual atc atc { get; set; }
    }
}
