//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip_receipt_views
    {
        public int id { get; set; }
        public Nullable<int> trip_registry_id { get; set; }
        public Nullable<int> view_count { get; set; }
    }
}
