//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip_sync
    {
        public long id { get; set; }
        public string trip_id { get; set; }
        public string plant { get; set; }
        public string atc { get; set; }
        public string delivery { get; set; }
        public string driverid { get; set; }
        public string source { get; set; }
        public string destination { get; set; }
        public string waybill { get; set; }
        public string wb_date { get; set; }
        public string wb_time { get; set; }
    }
}
