//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip_closure
    {
        public int id { get; set; }
        public string trip_id { get; set; }
        public string trip_id_sap { get; set; }
        public Nullable<decimal> damaged_qty { get; set; }
        public Nullable<decimal> caked_qty { get; set; }
        public Nullable<decimal> short_qty { get; set; }
        public string customer_no { get; set; }
        public Nullable<decimal> manual_km { get; set; }
        public string address { get; set; }
        public string waybill { get; set; }
        public Nullable<System.DateTime> closure_date { get; set; }
        public string status { get; set; }
        public Nullable<bool> posted_to_sap { get; set; }
        public Nullable<System.DateTime> sap_time { get; set; }
        public string miss_reason { get; set; }
    }
}
