//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip_registry_backup
    {
        public int Id { get; set; }
        public string trip_no { get; set; }
        public string cab_id { get; set; }
        public Nullable<int> driver_id { get; set; }
        public Nullable<int> truck_id { get; set; }
        public Nullable<int> atc_id { get; set; }
        public Nullable<int> clearance_id { get; set; }
        public Nullable<System.DateTime> creation_datetime { get; set; }
        public string contact_person { get; set; }
        public string source { get; set; }
        public string fleet_number { get; set; }
        public Nullable<double> fuel_allowed { get; set; }
        public Nullable<int> ship_to_party { get; set; }
        public Nullable<int> sold_to_party { get; set; }
        public string destination { get; set; }
        public Nullable<double> initial_km { get; set; }
        public Nullable<double> additional_km { get; set; }
        public Nullable<double> fuel_allowance1 { get; set; }
        public Nullable<double> fuel_allowance2 { get; set; }
        public Nullable<double> fuel_allowance3 { get; set; }
        public Nullable<double> fuel_allowance4 { get; set; }
        public string status { get; set; }
        public Nullable<int> transporter_id { get; set; }
    }
}
