//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class truck
    {
        public int Id { get; set; }
        public string truck_no { get; set; }
        public Nullable<bool> available { get; set; }
        public string cab_no { get; set; }
        public Nullable<bool> third_party { get; set; }
        public string company_name { get; set; }
        public string driver_name { get; set; }
        public string driver_id_no { get; set; }
    }
}
