//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class trx_data_audit
    {
        public int id { get; set; }
        public Nullable<int> trx_id { get; set; }
        public Nullable<System.DateTime> audit_date { get; set; }
        public string column_name { get; set; }
        public string old_value { get; set; }
        public string new_value { get; set; }
        public string username { get; set; }
    }
}
