//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_modification
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> change_request_id { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> new_role_id { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> new_active { get; set; }
        public Nullable<bool> admin { get; set; }
        public Nullable<bool> new_admin { get; set; }
        public string status { get; set; }
    }
}
