//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_back_up_27092021
    {
        public int Id { get; set; }
        public string username { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public string password { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> admin { get; set; }
        public Nullable<bool> approved { get; set; }
        public string department { get; set; }
        public Nullable<bool> can_approve { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public string status { get; set; }
    }
}
