//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.atc_session = new HashSet<atc_session>();
            this.atc_session1 = new HashSet<atc_session>();
            this.user_request = new HashSet<user_request>();
        }
    
        public int Id { get; set; }
        public string username { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public string password { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> admin { get; set; }
        public Nullable<bool> approved { get; set; }
        public string department { get; set; }
        public Nullable<bool> can_approve { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atc_session> atc_session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atc_session> atc_session1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_request> user_request { get; set; }
    }
}
