//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserList
    {
        public string userid { get; set; }
        public string logname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string validflag { get; set; }
        public string groupname { get; set; }
    }
}
