//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class vbbe
    {
        public int Id { get; set; }
        public string sales_document { get; set; }
        public string sales_document_item { get; set; }
        public string schedule_line_number { get; set; }
        public string material { get; set; }
        public string plant { get; set; }
        public Nullable<System.DateTime> material_avail_date { get; set; }
        public string sd_document_ceiling { get; set; }
        public string requirement_type { get; set; }
        public string planning_type { get; set; }
        public Nullable<decimal> open_quantity { get; set; }
        public Nullable<decimal> qty_for_avail_check { get; set; }
        public string base_unit_of_measure { get; set; }
        public string sales_document_type { get; set; }
        public string sold_to_party { get; set; }
    }
}
