//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class vbpa
    {
        public int Id { get; set; }
        public string sales_document { get; set; }
        public string item_sd { get; set; }
        public string partner_function { get; set; }
        public string customer { get; set; }
        public string vendor { get; set; }
        public string personal_number { get; set; }
        public string contact_person { get; set; }
        public string address { get; set; }
        public string unloading_point { get; set; }
        public string country_key { get; set; }
        public string address_indicator { get; set; }
    }
}
