//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_dispatch
    {
        public int Id { get; set; }
        public string delivery_no { get; set; }
        public string parent_so { get; set; }
        public string sales_doc_number { get; set; }
        public string sales_doc_type { get; set; }
        public string customer_no { get; set; }
        public string customer_name { get; set; }
        public string dispatch_plant { get; set; }
        public string material { get; set; }
        public string del_qty { get; set; }
        public string uom { get; set; }
        public string waybill { get; set; }
        public string truck_no { get; set; }
        public string drivers_name { get; set; }
        public string trip_id { get; set; }
        public string tare_weight { get; set; }
        public string gross_weight { get; set; }
        public string invoice_no { get; set; }
        public string truckno { get; set; }
        public string product { get; set; }
        public string specification { get; set; }
        public string sender { get; set; }
        public string receiver { get; set; }
        public Nullable<System.DateTime> grossdatetime { get; set; }
        public Nullable<System.DateTime> taredatetime { get; set; }
        public Nullable<decimal> gross { get; set; }
        public Nullable<decimal> tare { get; set; }
        public Nullable<decimal> net { get; set; }
        public Nullable<decimal> sparenum2 { get; set; }
        public Nullable<System.DateTime> firstdatetime { get; set; }
        public Nullable<System.DateTime> seconddatetime { get; set; }
        public Nullable<long> trade_id { get; set; }
        public string transporter { get; set; }
        public Nullable<decimal> firstweight { get; set; }
        public Nullable<decimal> secondweight { get; set; }
        public string transporter_name { get; set; }
        public string username1 { get; set; }
        public string username2 { get; set; }
        public string sparestr8 { get; set; }
    }
}
