//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_transactions
    {
        public int id { get; set; }
        public Nullable<int> atc_id { get; set; }
        public string transporter { get; set; }
        public string transporter_name { get; set; }
        public Nullable<decimal> sparenum2 { get; set; }
        public string sales_doc_number { get; set; }
        public string sales_doc_type { get; set; }
        public string truck_no { get; set; }
        public string delivery_no { get; set; }
        public string trip_id { get; set; }
        public string material { get; set; }
        public string customer_name { get; set; }
        public string customer_no { get; set; }
        public string del_qty { get; set; }
        public string doc_type { get; set; }
        public string doc_number { get; set; }
        public Nullable<System.DateTime> trx_datetime { get; set; }
    }
}
