//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_equipment_trip
    {
        public int id { get; set; }
        public string equipment { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string fleet_section { get; set; }
        public string object_type { get; set; }
        public string object_number { get; set; }
        public string chassis_number { get; set; }
        public string license_number { get; set; }
        public string primary_fuel { get; set; }
        public string secondary_fuel { get; set; }
        public string fleet { get; set; }
        public string tms_status { get; set; }
        public string tms_online_status { get; set; }
        public string atc_no { get; set; }
        public Nullable<System.DateTime> creation_datetime { get; set; }
        public string trip_no { get; set; }
        public string trip_id_sap { get; set; }
    }
}
