//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_atc_session_transaction
    {
        public int Id { get; set; }
        public string session_id { get; set; }
        public Nullable<System.DateTime> session_start { get; set; }
        public Nullable<int> start_approved_by { get; set; }
        public Nullable<System.DateTime> session_end { get; set; }
        public Nullable<int> end_approved_by { get; set; }
        public string status { get; set; }
        public int Expr1 { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> trx_date { get; set; }
        public string activity { get; set; }
        public string field_value { get; set; }
        public string atc { get; set; }
        public string field_name { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public string user_start_approved { get; set; }
        public string user_end_approved { get; set; }
        public string user_trx { get; set; }
    }
}
