//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_plot
    {
        public int id { get; set; }
        public Nullable<int> field_id { get; set; }
        public string plot_code { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string field_name { get; set; }
        public Nullable<decimal> field_area { get; set; }
        public Nullable<int> estate_id { get; set; }
        public string outgrower_name { get; set; }
        public string address { get; set; }
    }
}
