//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_driver_trip
    {
        public int Id { get; set; }
        public string driver_no { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string plant { get; set; }
        public Nullable<bool> available { get; set; }
        public Nullable<bool> third_party { get; set; }
        public string trip_no { get; set; }
        public string trip_id_sap { get; set; }
        public string atc_no { get; set; }
        public string tms_status { get; set; }
        public string tms_online_status { get; set; }
    }
}
