//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_estate_field
    {
        public int id { get; set; }
        public Nullable<int> estate_id { get; set; }
        public Nullable<int> field_id { get; set; }
        public string variety { get; set; }
        public string crop_cycle { get; set; }
        public Nullable<decimal> spacing { get; set; }
        public string code { get; set; }
        public string desscription { get; set; }
        public string field_name { get; set; }
        public Nullable<decimal> field_area { get; set; }
    }
}
