//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDS_Tz_Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class weight_switch
    {
        public int id { get; set; }
        public Nullable<int> change_request_id { get; set; }
        public Nullable<int> atc_id { get; set; }
        public Nullable<decimal> tare_weight { get; set; }
        public Nullable<decimal> gross_weight { get; set; }
        public string status { get; set; }
    }
}
